const express = require('express')
const PlaylistController = require('../controllers/playlistController')
const { authenticationTokenUser } = require('../middleware/authentication')
const validObjectId = require('../middleware/validObjectId')
const router = express.Router()

router.get('/playlist/favorite',authenticationTokenUser ,PlaylistController.userFavoritePlaylist)
router.get('/playlist/random', authenticationTokenUser, PlaylistController.getRandomPlaylist)
router.get('/playlist/:id', authenticationTokenUser, PlaylistController.getPlaylistById)
router.get('/', authenticationTokenUser, PlaylistController.getAllPlaylists)
router.post('/playlist', authenticationTokenUser, PlaylistController.createPlaylist)
router.put('/playlist/:id', authenticationTokenUser, validObjectId, PlaylistController.editPlaylistById)
router.put('/playlist/add/song', authenticationTokenUser, PlaylistController.addSongToPlaylist)
router.put('/playlist/remove/song', authenticationTokenUser, PlaylistController.removeSongFromPlaylist)
router.put('/playlist/:id', authenticationTokenUser, PlaylistController.removeSongFromPlaylist)
module.exports = router